### ISSUE TITLE
DDIA Presentation Date

### ISSUE THREAD

**Issue by evan361425** [evan361425/evan361425.github.io#19]
| 日期  | 星期 | 開始時間 | 會議室               | 主題                 |
| ----- | ---- | -------- | -------------------- | -------------------- |
| 12/09 | 四   | 1400     | 701                  | 簡介                 |
| 12/17 | 五   | 1400     | 三樓包廂 | 資料模型和語法       |
| 12/24 | 五   | 1400     | 701                  | 索引                 |
| 01/07 | 五   | 1400     | 402                  | 資料倉儲             |
| 01/14 | 五   | 1400     | 402                  | 編碼和進程           |
| 01/21 | 五   | 1400     | 402                  | 競賽情況             |
| 02/11 | 五   | 1400     | 402                  | 分散式資料庫—複製    |
| 02/18 | 五   | 1400     | 402                  | 分散式資料庫—分區    |
| 02/25 | 五   | 1400     | 402                  | 分散式系統遇到的狀況 |
| 03/04 | 五   | 1400     | 704      | 分散式系統的容錯     |
| 03/17 | 四   | 1500     | 701                  | 批次處理             |
| 03/25 | 五   | 1400     | 306                  | 串流處理                 |
| 04/01 | 五   | 1400     | 704      | 衍生資料的整合                 |

**Comment by yaosiang** [comment]
Great!

**Comment by evan361425** [comment]
## introduction feedback

- batch process 講得太分散
- consensus 講個大概就好了
- 輪廓先講清楚，旅程意義
- 英文發音

**Comment by sharonlinDTT** [comment]
請問去哪裡可以找到講義～

**Comment by evan361425** [comment]
https://github.com/Vonng/ddia 🤫

**Comment by evan361425** [comment]
## Index feedback

- memory v.s. disk/filesystem
- memory 叫**記憶體**不叫**內存**
